on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: daianatest.azurecr.io
        username: ${{ secrets.acr_daianatest_username }}
        password: ${{ secrets.acr_daianatest_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t daianatest.azurecr.io/syamaguchiaksclient2:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push daianatest.azurecr.io/syamaguchiaksclient2:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_syamaguchiaksclient2_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep syamaguchi-aks-client-2bd27 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace syamaguchi-aks-client-2bd27`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: syamaguchi-aks-client-2bd27
        container-registry-url: daianatest.azurecr.io
        container-registry-username: ${{ secrets.acr_daianatest_username }}
        container-registry-password: ${{ secrets.acr_daianatest_password }}
        secret-name: syamaguchiakdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: syamaguchi-aks-client-2bd27
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          daianatest.azurecr.io/syamaguchiaksclient2:${{ github.sha }}
        imagepullsecrets: |
          syamaguchiakdockerauth
