name: Image build and push.
# on: [push]
on:
  pull_request:
    # branches:
    #   - ${{ github.base_ref }}
    types: [closed]
jobs:
  Image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out to base_ref branch.
        uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}
      - run: |
          git branch -a
      - run: |
          echo "secrets.acr_daianatest_username=${{ secrets.acr_daianatest_username }}"
          echo "secrets.acr_daianatest_password=${{ secrets.acr_daianatest_password }}"
      - run: docker image ls
      - name: Set git HEAD commit ID.
        run: |
          export COMMIT_ID=$(git rev-parse HEAD)
          echo ${COMMIT_ID}
      - name: Set docker image name.
        run: |
          export IMAGE_NAME=daianatest.azurecr.io/${{ github.repository }}:${COMMIT_ID}
      - name: Build docker image for merged code.
        run: |
          docker image build -t ${IMAGE_NAME} .
      - name: Login to ACR.
        run: |
          docker login -u ${{ secrets.acr_daianatest_username }} -p ${{ secrets.acr_daianatest_password }}
      - name: Push to ACR.
        run: |
          docker image push ${IMAGE_NAME}

      # - run: docker image ls
      # - run: 'docker container run -i tmp1:tmp1 sh /app/exec_unittests.sh'
      # docker image build -t ${DOCKER_HUB_REPO}/${{ github.repository }}:${ghprbActualCommit} .
      # sh 'docker container run -i ${DOCKER_HUB_REPO}/${ghprbGhRepository}:${ghprbActualCommit} sh ${UNITTEST_EXECUTE_SHELL_FPATH}'
      # - run: echo "🍏 This job's status is ${{ job.status }}."
