name: Image build and push.
on:
  [pull_request]
  # # mainブランチにPRがmergeされる際にトリガーされる。
  # # つまり、mergeが完了したタイミングでJobが走る。
  # push:
  #   branches:
  #     - main
jobs:
  image-and-manifest-build-and-push:
    runs-on: ubuntu-latest
    outputs:
      has_diff: ${{ steps.check-mod-diff.outputs.has_diff }}
    strategy:
      matrix:
        modules:
          - mod_1
          - mod_2

      # １つのブランチに対して複数のcommitをSequentialに追加したいので、
      # 並列runを禁止する.
      max-parallel: 1

    env:
      DOCKER_REGISTRY: daianatest.azurecr.io
    steps:
      - name: Check out to base_ref branch.
        uses: actions/checkout@v2
        with:
          # Note: Merge後のBaseブランチを用いてDocker imageを作りたいので、
          #       base_refにcheckoutする。
          ref: ${{ github.base_ref }}

          # Mergeの１つ前の状態も確認するため、depth=2とする.
          fetch-depth: 2
      - name: Check the mod has diff.
        id: check-mod-diff
        run: |
          diff_result=$(git diff --name-only \
            HEAD~ \
            | grep -E '^${{ matrix.modules }}/.*' \
            || true)
          if [ ! -z "$diff_result" ]; then
            HAS_DIFF='1'
          else
            HAS_DIFF='0'
          fi
          echo HAS_DIFF=${HAS_DIFF}
          echo "HAS_DIFF=$HAS_DIFF" >> $GITHUB_ENV
          echo "::set-output name=has_diff::$HAS_DIFF"
      - name: Set env - git HEAD commit ID.
        if: ${{ env.HAS_DIFF == '1' }}
        run: |
          echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - name: Set env - docker image name.
        if: ${{ env.HAS_DIFF == '1' }}
        run: |
          IMAGE_NAME="${{ env.DOCKER_REGISTRY }}/${{ github.repository }}"
          IMAGE_NAME+="/${{ matrix.modules }}"
          IMAGE_NAME+=":$(date +"%Y-%m-%d_%H-%M-%S-%Z")-${{ env.COMMIT_ID }}"
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
      - name: Load Dockerfile base image name.
        if: ${{ env.HAS_DIFF == '1' }}
        run: |
          cd ${{ matrix.modules }}
          BASE_IMAGE=$( ./get_base_image.sh "${{ env.DOCKER_REGISTRY }}" )
          echo "BASE_IMAGE=$BASE_IMAGE" >> $GITHUB_ENV
      - name: Login to ACR.
        if: ${{ env.HAS_DIFF == '1' }}
        run: |
          docker login ${{ env.DOCKER_REGISTRY }} \
            -u ${{ secrets.acr_daianatest_username }} \
            -p ${{ secrets.acr_daianatest_password }}
      - name: Build docker image for merged code.
        if: ${{ env.HAS_DIFF == '1' }}
        run: |
          cd ${{ matrix.modules }}
          docker image build \
            -t ${{ env.IMAGE_NAME }} \
            --build-arg base_image=${{ env.BASE_IMAGE }} .
      - name: Push to ACR.
        if: ${{ env.HAS_DIFF == '1' }}
        run: |
          docker image push ${{ env.IMAGE_NAME }}
      - name: Check out cluster repo.
        if: ${{ env.HAS_DIFF == '1' }}
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 既存のfeature branchを参照したい場合がある為.
          repository: 'shinbero/hello-world-cluster'

          # 別repositryでPushもしたい場合は、
          # このWorkflowのデフォルトのトークン(GITHUB_TOKEN)では403 errorとなる為,
          # 対象repoにwrite権限があるTOKENを利用する.
          token: ${{ secrets.CLUSTER_REPO_TOKEN }}
      - name: Create manifest of the mod.
        if: ${{ env.HAS_DIFF == '1' }}
        run: |
          template_manifest=manifests/template/${{ matrix.modules }}.template.yml
          generated_manifest=manifests/${{ matrix.modules }}.yml
          cat ${template_manifest} \
            | sed -e "s#%%__IMAGE__%%#${{ env.IMAGE_NAME }}#g" \
            > ${generated_manifest}
      - name: Checkout to feature branch & commit & push to cluster repo.
        if: ${{ env.HAS_DIFF == '1' }}
        run: |
          # Branch名は、どのActionで走ったか特定できるような名前にする.
          branch_name=${{ github.repository }}/actions/runs/${{ github.run_id }}

          feature_branch_exists=$(git branch -a | grep ${branch_name} || true)
          if [ ! -z ${feature_branch_exists} ]; then
            # The branch already exists.
            git checkout ${branch_name}
          else
            # まだ対象のbranchが存在しないので、作成してcheckout.
            git checkout -b ${branch_name}
          fi
          git diff
          git add .
          git config --global user.name "tmp"
          git config --global user.email "tmp@example.com"
          git commit -m "Created new manifest in ${branch_name}"
          git push -u origin ${branch_name}
      # - uses: actions/cache@v2
      #   id: cache
      #   with:
      #     path: path/to/dependencies
      #     key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
  
  create-pr-of-cluster:
    needs: image-and-manifest-build-and-push
    if: always()
    runs-on: ubuntu-latest
    steps:
      # - name: Download Artifacts
      #   uses: actions/download-artifact@v2
      #   with:
      #     path: artifacts

      - name: Create PR to cluster repo. <- This should not be done in matrix.
        # if: ${{ env.HAS_DIFF == '1' }}
        run: |
          echo ${{needs.image-and-manifest-build-and-push.outputs.has_diff}}

