on: [pull_request]
  # pull_request:
    # branches:
    #   - master
    # types: [closed]
jobs:
  build:
    name: Build-job
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "https://syamguchi-appgw.japanwest.cloudapp.azure.com"
        user: "syamaguchi"
        token: ${{ secrets.JENKINS_SYAMAGUCHI_TOKEN }}
      job: "GitHub-after-merge"
